### ISSUE TITLE
Code annotations fail to render with `techdocs-core` plugin enabled

### ISSUE THREAD

**Issue by rmartine-ias** [backstage/mkdocs-techdocs-core#128] opened 2023-06-08 21:57 UTC
Something `techdocs-core` is doing (maybe [setting](https://github.com/backstage/mkdocs-techdocs-core/commit/ec5dcc17c917a383f8b43e3ce11484c17491bcfd) `theme.palette` to `''`?) prevents [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) from rendering.

Reproduction:
```shell
python3.11 -m venv .venv
source .venv/bin/activate
pip install mkdocs-techdocs-core
mkdir docs
```

`mkdocs.yml`:

```yaml
site_name: Backstage Docs
theme:
  name: material
  features:
    - content.code.annotate
nav:
  - Home: index.md
markdown_extensions:
  - pymdownx.superfences
```

`docs/index.md`:

    ```yaml
    # (1)
    ```

    1. An annotation

```shell
mkdocs build
open site/index.html # You should see a clickable annotation
yq -i '.plugins[0] = "techdocs-core"' mkdocs.yml
mkdocs build
open site/index.html # You should not see an annotation
```

Without techdocs:
<img width="487" alt="Screenshot 2023-06-08 at 3 54 20 PM" src="https://github.com/backstage/mkdocs-techdocs-core/assets/107639398/6f0fa328-fc3d-4f62-bdf7-3891b7067dd0">

With it:
<img width="164" alt="Screenshot 2023-06-08 at 3 54 24 PM" src="https://github.com/backstage/mkdocs-techdocs-core/assets/107639398/4f8d7e23-0b3a-47cc-9dc3-4ac1da8763f6">

I noticed that if I have no plugins set, and set `theme.palette` to `""`, then annotations also fail to render. So I think this might be causing it, but don't see an easy fix.

**Comment by steven-terrana-bah** [comment] 2023-07-28 12:51
I came to the same conclusion that this issue was being caused by `theme.palette: ""` so i tried creating a hook that overrides this value _after_ the `techdocs-core` plugin makes its configuration changes (just to see what would happen).

This fixed code annotation rendering on the mkdocs site directly (`http://localhost:8000`) but **not** in the techdocs rendering within backstage (`http://localhost:3000`) when running `techdocs-cli serve`.

**mkdocs.yml**
``` yaml
site_name: test-annotations

theme:
  name: material
  features:
    - content.code.annotate  
  palette.scheme: default

plugins: 
 - techdocs-core

hooks:
- hooks.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - home: index.md
```

**hook.py**
``` py
import mkdocs

@mkdocs.plugins.event_priority(-100)
def on_config(config):
    config['theme']['palette'] = {}
    config['theme']['palette']['scheme'] = 'default'
    return config
```

**Comment by Gholie** [comment] 2023-10-03 11:01
We are looking to use annotations as well. Related issue #145 for updates on core packages relevant as well

**Comment by alexlorenzi** [comment] 2023-11-20 19:14
Hi, @rmartine-ias.
Thanks for spotting this, it certainly does mess up the HTML generated. We have an [update](https://github.com/backstage/mkdocs-techdocs-core/pull/154/files#diff-d2f3f938b280b4e18aeb27c01f9715ae7b35538754a0209dde6f5c365308a88cL73-R73) going in that will fix this issue.

However, two other issues mean the annotations don't display from within Backstage: 

First, we [sanitize the HTML](https://github.com/backstage/backstage/blob/b5ae2e5a62d61f188e1f7b6ac4aeabb8429c6f89/plugins/techdocs/src/reader/components/TechDocsReaderPageContent/dom.tsx#L142) rendered by MkDocs in the TechDoc plugin before we display it on the page. This will remove the script tags that are generated by the plugin for the annotations. 

Second, even if we modified the sanitization to keep the scripts, the way the rendered DOM is attached to the page still means that the javascript doesn't execute. We use the [DomParser](https://github.com/backstage/backstage/blob/b5ae2e5a62d61f188e1f7b6ac4aeabb8429c6f89/plugins/techdocs/src/reader/transformers/transformer.ts#L26) to convert the HTML string into DOM elements, and through this, any script tags get marked as [unexecutable](https://www.w3.org/TR/DOM-Parsing/#widl-DOMParser-parseFromString-Document-DOMString-str-SupportedType-type).

Because of this, we'd require quite a drastic change to how the frontend plugin works to enable this, so it's not something we can support currently.

**Closed** 2023-11-21 15:47 UTC

**Comment by vanchaxy** [comment] 2024-09-28 04:48
It's not perfect but I made it work using addon. Most of the code copied from mkdocs material.

![ezgif-2-d103e08132](https://github.com/user-attachments/assets/238d67ba-a776-4e82-8833-3c699bed8cf9)

Code:
```import {useEffect, useState} from 'react';
import { useShadowRootElements } from '@backstage/plugin-techdocs-react';
import ReactDOM from "react-dom/client";
import React from 'react';

import Popover from '@material-ui/core/Popover';

function findHosts(container: HTMLElement): HTMLElement[] {
  return container.tagName === "CODE"
    ? Array.from(container.querySelectorAll(".c, .c1, .cm"))
    : [container]
}

function findMarkers(container: HTMLElement): Text[] {
  const markers: Text[] = []
  console.log(findHosts(container))
  for (const el of findHosts(container)) {
    const nodes: Text[] = []

    /* Find all text nodes in current element */
    const it = document.createNodeIterator(el, NodeFilter.SHOW_TEXT)
    for (let node = it.nextNode(); node; node = it.nextNode())
      nodes.push(node as Text)

    /* Find all markers in each text node */
    for (let text of nodes) {
      let match: RegExpExecArray | null

      /* Split text at marker and add to list */
      while ((match = /(\(\d+\))(!)?/.exec(text.textContent!))) {
        const [, id, force] = match
        if (typeof force === "undefined") {
          const marker = text.splitText(match.index)
          text = marker.splitText(id.length)
          markers.push(marker)

        /* Replace entire text with marker */
        } else {
          text.textContent = id
          markers.push(text)
          break
        }
      }
    }
  }
  return markers
}

function findCandidateList(el: HTMLElement): HTMLElement | undefined {
  if (el.nextElementSibling) {
    const sibling = el.nextElementSibling as HTMLElement
    if (sibling.tagName === "OL")
      return sibling

    /* Skip empty paragraphs - see https://bit.ly/3r4ZJ2O */
    else if (sibling.tagName === "P" && !sibling.children.length)
      return findCandidateList(sibling)
  }

  /* Everything else */
  return undefined
}

function getOptionalElement<T extends HTMLElement>(
  selector: string, node: ParentNode = document
): T | undefined {
  return node.querySelector<T>(selector) || undefined
}


function AnnotationPopover({ content }: { content: any }) {
  const [anchor, setAnchor] = React.useState(null);

  const handleClick = (event: any) => {
    setAnchor(event.currentTarget);
  };

  const handleClose = () => {
    setAnchor(null);
  };

  const open = Boolean(anchor);
  const id = open ? 'annotation-popover' : undefined;

  return (
    <>
      <span
          className="md-annotation__index"
          style={{}}
          onClick={handleClick}
      >
        <span data-md-annotation-id=''></span>
      </span>
      <Popover
        id={id}
        open={open}
        anchorEl={anchor}
        onClose={handleClose}
        anchorOrigin={{
          vertical: 'center',
          horizontal: 'center',
        }}
        transformOrigin={{
          vertical: 'top',
          horizontal: 'left',
        }}
      >
        <div
            style={{'padding': '.8rem', 'maxWidth': 'calc(100vw - 1.6rem)', 'width': '20rem'}}
            dangerouslySetInnerHTML={{ __html: content }}>
        </div>
      </Popover>
    </>
  );
}

export const AnnotationAddon = () => {
  const containers = useShadowRootElements<HTMLImageElement>(['.annotate', 'pre:not(.mermaid) > code']);
  const heads = useShadowRootElements<HTMLImageElement>(['head']);
  const [cssAdded, setCssAdded] = useState<boolean>(false);

  useEffect(() => {
      for (let container of containers) {
        let annotationsList;
        if (container.tagName === 'CODE') {
          const highlight = container.closest('.highlight');
           if (!(highlight instanceof HTMLElement)) return;
          annotationsList = findCandidateList(highlight);
        } else {
          annotationsList = findCandidateList(container);
        }
        if (!annotationsList) return;
        for (const marker of findMarkers(container)) {
          const [, id] = marker.textContent!.match(/\((\d+)\)/)!
          const popup = getOptionalElement(`:scope > li:nth-child(${id})`, annotationsList);
          if (popup) {
            const aside = document.createElement('aside');
            aside.className = 'md-annotation';
            marker.replaceWith(aside);
            const root = ReactDOM.createRoot(aside)
            root.render(<AnnotationPopover content={popup.innerHTML} />);
          }
        }
        annotationsList.remove()
      }
  }, [containers]);

    useEffect(() => {
    if (cssAdded) return;
    const styleElement = document.createElement('style');
    styleElement.innerText = `
    :host {
      --md-annotation-bg-icon: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2A10 10 0 0 0 2 12a10 10 0 0 0 10 10 10 10 0 0 0 10-10A10 10 0 0 0 12 2Z"/></svg>');
      --md-annotation-icon: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17 13h-4v4h-2v-4H7v-2h4V7h2v4h4m-5-9A10 10 0 0 0 2 12a10 10 0 0 0 10 10 10 10 0 0 0 10-10A10 10 0 0 0 12 2Z"/></svg>')
    }
    `;

    heads.forEach((head) => {
      head.parentNode?.insertBefore(styleElement, head.nextSibling);
    });
    setCssAdded(true);
  }, [heads, cssAdded]);

  return null;
};
```
